### ISSUE TITLE
Заражённый файл.

### ISSUE THREAD

**Issue by Amaderis** [FAR747/XIVRUS_Updater#4]
Разрешите эту проблему. В дисе уже тоже скинул сообщение. Но игнорят админы. 

![изображение](https://github.com/xivrus/XIVRus_Updater/assets/120781153/55862cff-ae43-400d-a3cf-6c0727a7441f)

**Comment by FAR747** [comment]
Данная проблема связана с [Clowd.Squirrel](https://github.com/clowd/Clowd.Squirrel/issues/28). 
Антивирусам не нравится, что установщик является самораспаковывающимся архивом.  
Увы я не могу её исправить. 
Хотя я думаю о том, чтобы написать свой установщик с автообновлением утилиты если проблема будет беспокоить многих.

**Comment by Amaderis** [comment]
> Данная проблема связанна с [Clowd.Squirrel ](https://github.com/clowd/Clowd.Squirrel/issues/28). Антивирусам не нравится, что установщик является самораспаковывающимся архивом. Увы я не могу её исправить. Хотя я думаю о том, чтобы написать свой установщик с автообновлением утилиты если проблема будет беспокоить многих.

Ну я подозревал что именно из-за этого. Так-то утилита годная. И ускоряет установку руссика. Но не все будут понимать почему антивир ругается. Так что моё дело сообщить :)

**Comment by FAR747** [comment]
> Ну я подозревал что именно из-за этого. Так-то утилита годная. И ускоряет установку руссика. Но не все будут понимать почему антивир ругается. Так что моё дело сообщить :)

Я напишу об этом в ReadMe и FAQ
